window.RUBIKS_ALGORITHMS = {
  OLL: [
    { id: "OLL 1", group: "點形", algorithm: "R U2 R2 F R F' U2 R' F R F'" },
    { id: "OLL 2", group: "點形", algorithm: "F R U R' U' F' f R U R' U' f'" },
    { id: "OLL 3", group: "點形", algorithm: "f R U R' U' f' U' F R U R' U' F'" },
    { id: "OLL 4", group: "點形", algorithm: "f R U R' U' f' U F R U R' U' F'" },
    { id: "OLL 5", group: "方形", algorithm: "r' U2 R U R' U r" },
    { id: "OLL 6", group: "方形", algorithm: "r U2 R' U' R U' r'" },
    { id: "OLL 7", group: "小閃電", algorithm: "r U R' U R U2 r'" },
    { id: "OLL 8", group: "小閃電", algorithm: "r' U' R U' R' U2 r" },
    { id: "OLL 9", group: "魚形", algorithm: "R U R' U' R' F R2 U R' U' F'" },
    { id: "OLL 10", group: "魚形", algorithm: "R U R' U R' F R F' R U2 R'" },
    { id: "OLL 11", group: "小閃電", algorithm: "r' R2 U R' U R U2 R' U M'" },
    { id: "OLL 12", group: "小閃電", algorithm: "M U2 R' U' R U' R' U2 R U M'" },
    { id: "OLL 13", group: "騎士形", algorithm: "F U R U' R2 F' R U R U' R'" },
    { id: "OLL 14", group: "騎士形", algorithm: "R' F R U R' F' R F U' F'" },
    { id: "OLL 15", group: "騎士形", algorithm: "r' U' r R' U' R U r' U r" },
    { id: "OLL 16", group: "騎士形", algorithm: "r U r' R U R' U' r U' r'" },
    { id: "OLL 17", group: "點形", algorithm: "R U R' U R' F R F' U2 R' F R F'" },
    { id: "OLL 18", group: "點形", algorithm: "r U R' U R U2 r2 U' R U' R' U2 r" },
    { id: "OLL 19", group: "點形", algorithm: "M U R U R' U' M' R' F R F'" },
    { id: "OLL 20", group: "點形", algorithm: "M U R U R' U' M2 U R U' r'" },
    { id: "OLL 21", group: "角塊定向", algorithm: "R U2 R' U' R U R' U' R U' R'" },
    { id: "OLL 22", group: "角塊定向", algorithm: "R U2 R2 U' R2 U' R2 U2 R" },
    { id: "OLL 23", group: "角塊定向", algorithm: "R2 D R' U2 R D' R' U2 R'" },
    { id: "OLL 24", group: "角塊定向", algorithm: "r U R' U' r' F R F'" },
    { id: "OLL 25", group: "角塊定向", algorithm: "F' r U R' U' r' F R" },
    { id: "OLL 26", group: "Anti-Sune", algorithm: "R' U' R U' R' U2 R" },
    { id: "OLL 27", group: "Sune", algorithm: "R U R' U R U2 R'" },
    { id: "OLL 28", group: "箭頭形", algorithm: "M' U M U2 M' U M" },
    { id: "OLL 29", group: "特殊形", algorithm: "M U R U R' U' R' F R F' M'" },
    { id: "OLL 30", group: "特殊形", algorithm: "R2 U R' B' R U' R2 U R B R'" },
    { id: "OLL 31", group: "P 形", algorithm: "R' U' F U R U' R' F' R" },
    { id: "OLL 32", group: "P 形", algorithm: "R U B' U' R' U R B R'" },
    { id: "OLL 33", group: "T 形", algorithm: "R U R' U' R' F R F'" },
    { id: "OLL 34", group: "C 形", algorithm: "R U R2 U' R' F R U R U' F'" },
    { id: "OLL 35", group: "魚形", algorithm: "R U2 R2 F R F' R U2 R'" },
    { id: "OLL 36", group: "W 形", algorithm: "L' U' L U' L' U L U L F' L' F" },
    { id: "OLL 37", group: "魚形", algorithm: "F R U' R' U' R U R' F'" },
    { id: "OLL 38", group: "W 形", algorithm: "R U R' U R U' R' U' R' F R F'" },
    { id: "OLL 39", group: "大閃電", algorithm: "L F' L' U' L U F U' L'" },
    { id: "OLL 40", group: "大閃電", algorithm: "R' F R U R' U' F' U R" },
    { id: "OLL 41", group: "特殊形", algorithm: "R U R' U R U2 R' F R U R' U' F'" },
    { id: "OLL 42", group: "特殊形", algorithm: "R' F R F' R' F R F' R U R' U' R U R'" },
    { id: "OLL 43", group: "P 形", algorithm: "R' U' F R' F' R U R" },
    { id: "OLL 44", group: "P 形", algorithm: "f R U R' U' f'" },
    { id: "OLL 45", group: "T 形", algorithm: "F R U R' U' F'" },
    { id: "OLL 46", group: "C 形", algorithm: "R' U' R' F R F' U R" },
    { id: "OLL 47", group: "L 形", algorithm: "R' U' R' F R F' R' F R F' U R" },
    { id: "OLL 48", group: "L 形", algorithm: "F R U R' U' R U R' U' F'" },
    { id: "OLL 49", group: "L 形", algorithm: "r U' r2 U r2 U r2' U' r" },
    { id: "OLL 50", group: "L 形", algorithm: "r' U r2 U' r2' U' r2 U r'" },
    { id: "OLL 51", group: "I 形", algorithm: "f R U R' U' R U R' U' f'" },
    { id: "OLL 52", group: "I 形", algorithm: "R U R' U R d' R U' R' F'" },
    { id: "OLL 53", group: "L 形", algorithm: "r' U' R U' R' U R U' R' U2 r" },
    { id: "OLL 54", group: "L 形", algorithm: "r U R' U R U' R' U R U2 r'" },
    { id: "OLL 55", group: "I 形", algorithm: "R U2 R2 U' R U' R' U2 F R F'" },
    { id: "OLL 56", group: "I 形", algorithm: "r' U' r U' R' U R U' R' U R r' U r" },
    { id: "OLL 57", group: "H 形", algorithm: "R U R' U' M' U R U' r'" },
  ],
  PLL: [
    { id: "Aa", group: "角塊交換", algorithm: "x R' U R' D2 R U' R' D2 R2 x'" },
    { id: "Ab", group: "角塊交換", algorithm: "x R2 D2 R U R' D2 R U' R x'" },
    { id: "E", group: "對角交換", algorithm: "x' R U' R' D R U R' D' R U R' D R U' R' D' x" },
    { id: "F", group: "相鄰交換", algorithm: "R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R" },
    { id: "Ga", group: "G Perm", algorithm: "R2 U R' U R' U' R U' R2 D U' R' U R D'" },
    { id: "Gb", group: "G Perm", algorithm: "R' U' R U D' R2 U R' U R U' R U' R2 D" },
    { id: "Gc", group: "G Perm", algorithm: "R2 U' R U' R U R' U R2 D' U R U' R' D" },
    { id: "Gd", group: "G Perm", algorithm: "R U R' U' D R2 U' R U' R' U R' U R2 D'" },
    { id: "H", group: "邊塊交換", algorithm: "M2 U M2 U2 M2 U M2" },
    { id: "Ja", group: "相鄰交換", algorithm: "R' U L' U2 R U' R' U2 R L" },
    { id: "Jb", group: "相鄰交換", algorithm: "R U R' F' R U R' U' R' F R2 U' R'" },
    { id: "Na", group: "對角交換", algorithm: "R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'" },
    { id: "Nb", group: "對角交換", algorithm: "R' U R U' R' F' U' F R U R' F R' F' R U' R" },
    { id: "Ra", group: "相鄰交換", algorithm: "R U' R' U' R U R D R' U' R D' R' U2 R'" },
    { id: "Rb", group: "相鄰交換", algorithm: "R' U2 R U2 R' F R U R' U' R' F' R2" },
    { id: "T", group: "相鄰交換", algorithm: "R U R' U' R' F R2 U' R' U' R U R' F'" },
    { id: "Ua", group: "邊塊交換", algorithm: "R U' R U R U R U' R' U' R2" },
    { id: "Ub", group: "邊塊交換", algorithm: "R2 U R U R' U' R' U' R' U R'" },
    { id: "V", group: "對角交換", algorithm: "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2" },
    { id: "Y", group: "對角交換", algorithm: "F R U' R' U' R U R' F' R U R' U' R' F R F'" },
    { id: "Z", group: "邊塊交換", algorithm: "M2 U' M2 U' M' U2 M2 U2 M' U2" },
  ],
};
